<?php
$int_blog=2;
$int_photo=1;
$int_com_msg=1;
$int_subject=2;
$int_com_sub=1;
$int_del_blog=-2;
$int_del_photo=-1;
$int_del_com_msg=-1;
$int_del_subject=-2;
$int_del_com_sub=-1;
$int_invited=20;
$int_login=10;
$int_one_ico=40;
$int_convert=100;
$int_upgrade=5;
$int_poll=2;
$int_del_poll=-2;
$int_share=2;
$int_del_share=-2;
?>