<?php
class bloglp{
	var $b_blog="日志";
	var $b_mine="我的日志";
	var $b_friend="好友日志";
	var $b_creat="新建日志";
	var $b_edit="编辑";
	var $b_lock="该日志已经被锁定";
	var $b_search="日志搜索";
	var $b_re_list="返回日志列表";
	var $b_scan="浏览日志";
	var $b_add_suc="提交日志成功";
	var $b_add_fal="提交日志失败,请重新提交";
	var $b_edit_suc="修改日志成功!";
	var $b_edit_false="修改日志失败!";
	var $b_del_suc="删除日志成功";
	var $b_del_false="删除日志失败!";
	var $b_no_pass="请认真填写每个选项";
	var $b_manage_sort="日志分类";
	var $b_def_sort="默认分类 (不支持编辑及删除)";
	var $b_del_sort_suc="删除分类成功";
	var $b_change_sort_suc="修改分类成功";
	var $b_change_sort_false="修改分类失败";
	var $b_only_fri_com="仅能作者的好友评论";
	var $b_not_com="此日志不能进行评论";
	var $b_num="有{num}篇日志";
	var	$b_title="标题";
	var $b_sort="分类";
	var $b_author="作者";
	var $b_default_sort="默认分类";
	var $b_com_num="评论({b_com_num})";
	var $b_read_num="阅读({b_read_num})";
	var $b_no_fri_blog="对不起，当前没有您可以查看的日志";
	var $b_del="删除";
	var $b_a_del="是否删除?";
	var $b_button_save="保存";
	var $b_button_cancel="取消";
	var $b_none="您还没有添加日志,<a href='modules.php?app=blog_edit'>创建日志</a>,或者<a href='modules.php?app=blog_friend'>浏览好友的日志</a>";
	var $b_limit="权限";
	var $b_same_sort="查看同分类的日志";
	var $b_public="公开";
	var $b_private="仅自己";
	var $b_pals="仅好友";
	var $b_error="您访问的页面信息不存在";
	var $b_empty="请填写信息";
	var $b_limit_blog="由于该日志设置了权限，您无法访问";
	var $b_they_com="网友评论";
	var $b_send_time="发表于:{date_time}";
	var $b_i_com="我要评论";
	var $b_button_re="回复";
	var $b_button_clear="清除";
	var $b_add_sort="添加分类";
	var $b_content="内容";
	var $b_pic="图片";
	var $b_sel_album="（直接从相册中选择图片上传）";
	var $b_button_sure="确定";
	var $b_empty_t="请填写标题";
	var $b_empty_content="请填写内容";
	var $b_his_blog="{holder}的日志";
	var $b_re_suc="评论成功";
	var $b_re_last="返回上一级";
	var $b_face="表情";
	var $b_pri="隐私";
	
	var $b_content_not_saved="您填写的内容尚未保存!";
	var $b_label="标签";
	var $b_set_permissions="设置访问权限";
	var $b_data_loading="数据加载中,请稍侯...";
	var $b_share="分享";
	var $b_report="举报";	
	var $b_right_set_competence="点击右键设置访问权限";
	var $b_write_new_log = "写了新日志";
	
};
?>