<?php
class bloglp{
	var $b_blog="课程";
	var $b_mine="我的课程";
	var $b_friend="好友课程";
	var $b_creat="新建课程";
	var $b_edit="编辑";
	var $b_lock="该课程已经被锁定";
	var $b_search="课程搜索";
	var $b_re_list="返回课程列表";
	var $b_scan="浏览课程";
	var $b_add_suc="提交课程成功";
	var $b_add_fal="提交课程失败,请重新提交";
	var $b_edit_suc="修改课程成功!";
	var $b_edit_false="修改课程失败!";
	var $b_del_suc="删除课程成功";
	var $b_del_false="删除课程失败!";
	var $b_no_pass="请认真填写每个选项";
	var $b_manage_sort="课程类别";
	var $b_def_sort="默认类别 (不支持编辑及删除)";
	var $b_del_sort_suc="删除类别成功";
	var $b_change_sort_suc="修改类别成功";
	var $b_change_sort_false="修改类别失败";
	var $b_only_fri_com="仅能作者的好友评论";
	var $b_not_com="此课程不能进行评论";
	var $b_num="有{num}篇课程";
	var	$b_title="课程名";
	var $b_sort="课程类别";
	var $b_author="作者";
	var $b_default_sort="默认类别";
	var $b_com_num="评论({b_com_num})";
	var $b_read_num="浏览({b_read_num})";
	var $b_no_fri_blog="对不起，当前没有您可以查看的课程";
	var $b_del="删除";
	var $b_a_del="是否删除?";
	var $b_button_save="保存";
	var $b_button_cancel="取消";
	var $b_none="您还没有添加课程,<a href='modules.php?app=blog_edit'>创建课程</a>,或者<a href='modules.php?app=blog_friend'>浏览好友的课程</a>";
	var $b_limit="权限";
	var $b_same_sort="查看同类别的课程";
	var $b_public="公开";
	var $b_private="仅自己";
	var $b_pals="仅好友";
	var $b_error="您访问的页面信息不存在";
	var $b_empty="请填写信息";
	var $b_limit_blog="由于该课程设置了权限，您无法访问";
	var $b_they_com="网友评论";
	var $b_send_time="发表于:{date_time}";
	var $b_i_com="我要评论";
	var $b_button_re="回复";
	var $b_button_clear="清除";
	var $b_add_sort="添加类别";
	var $b_content="课程介绍";
	var $b_pic="图片";
	var $b_sel_album="（直接从相册中选择图片上传）";
	var $b_button_sure="确定";
	var $b_empty_t="请填写标题";
	var $b_empty_content="请填写课程介绍";
	var $b_his_blog="{holder}的课程";
	var $b_re_suc="评论成功";
	var $b_re_last="返回上一级";
	var $b_face="表情";
	var $b_pri="隐私";
	
	var $b_content_not_saved="您填写的课程介绍尚未保存!";
	var $b_label="标签";
	var $b_set_permissions="设置访问权限";
	var $b_data_loading="数据加载中,请稍侯...";
	var $b_share="分享";
	var $b_report="举报";	
	var $b_right_set_competence="点击右键设置访问权限";
	var $b_write_new_log = "创建了新课程";
	
};
?>